docker export -o /data/fengwenhan/fav-hdfs/C1NN.tar C1NN
docker export -o /data/fengwenhan/fav-hdfs/C1RM.tar C1RM
docker export -o /data/fengwenhan/fav-hdfs/C1Master1.tar C1Master1
docker export -o /data/fengwenhan/fav-hdfs/C1Master2.tar C1Master2
docker export -o /data/fengwenhan/fav-hdfs/C1Slave1.tar C1Slave1
docker export -o /data/fengwenhan/fav-hdfs/C1Slave2.tar C1Slave2
docker export -o /data/fengwenhan/fav-hdfs/C1Slave3.tar C1Slave3
docker export -o /data/fengwenhan/fav-hdfs/C1Slave4.tar C1Slave4
docker export -o /data/fengwenhan/fav-hdfs/C1HS.tar C1HS
docker export -o /data/fengwenhan/fav-hdfs/C1WPS.tar C1WPS
docker export -o /data/fengwenhan/fav-hdfs/C1hd-zk.tar C1hd-zk