# version: "3"
version: "3.5"

# name: fav


services:
  C1RT1:
    image: fwhdzh/c1zk1
    networks:
      fav-raft:
        ipv4_address: 172.25.0.2
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1RT1
    # env_file: ~/code/faultfuzz/script/raft-java/.env
    # deploy:
    #   mode: replicated
    #   replicas: 6
    

  C1RT2:
    image: fwhdzh/c1zk2
    networks:
      fav-raft:
        ipv4_address: 172.25.0.3
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1RT2

  C1RT3:
    image: fwhdzh/c1zk3
    networks:
      fav-raft:
        ipv4_address: 172.25.0.4
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1RT3

  C1RT4:
    image: fwhdzh/c1zk4
    networks:
      fav-raft:
        ipv4_address: 172.25.0.5
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1RT4

  C1RT5:
    image: fwhdzh/c1zk5
    networks:
      fav-raft:
        ipv4_address: 172.25.0.6
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1RT5
    

networks:
  fav-raft:
    name: fav-raft
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.0/24


# docker-compose -p fav -f ~/code/faultfuzz/script/raft-java/raft-compose.yaml up -d
# docker-compose -p fav -f ~/code/faultfuzz/script/raft-java/raft-compose.yaml down
# docker-compose -p fav -f ~/code/faultfuzz/script/raft-java/raft-compose.yaml exec C1RT1 /bin/bash