WORKLOAD=zk1.sh
CRASH=crashNode.sh
CHECKER=zk1checker.sh
RESTART=startNode.sh
#BUG_REPORT=/data/gaoyu/faultfuzzer/zk-3.8.1-c1/crash-report
ROOT_DIR=/home/fengwenhan/data/faultfuzz_zk
CUR_FAULT_FILE=zk363curFault
MONITOR=monitor.sh
PRETREATMENT=prepareEnv.sh
UPDATE_FAULT=updateCurFault.sh
TEST_TIME=80h
#FAULT_CONFIG=1:{ip1,ip2,ip3};2:{ip4,ip5}
FAULT_CSTR=2:{172.40.0.2,172.40.0.3,172.40.0.4,172.40.0.5,172.40.0.6}
#MAP_SIZE=10000
AFL_PORT=12081
#millisecond
#WINDOW_SIZE=1000
HANG_TMOUT=5m
MAX_FAULTS=10

REPLAY_MODE=false

DETERMINE_WAIT_TIME=30000

WRITE_FAV_ENV=write-fav-env.sh
COPY_ENV_TO_CLUSTER=copy-env-to-cluster.sh

# COPY_LOGS_TO_CONTROLLER=copy-logs-to-controller.sh
# CLUSTER_LOGS_IN_CONTROLLER_DIR=/home/fengwenhan/data/faultfuzz_zk_logs

# RECOVERY_MODE=true
# RECOVERY_DIR=/home/fengwenhan/data/faultfuzz_zk_recovery

NETWORK_DISCONNECTION=network-disconnect.sh
NETWORK_CONNECTION=network-connect.sh

EVALUATE_TARGET=FaultFuzzer

