WORKLOAD=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/zk1.sh
CRASH=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/crashNode.sh
CHECKER=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/zk1checker.sh
RESTART=//home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/startNode.sh
#BUG_REPORT=/data/gaoyu/crashfuzzer/zk-3.8.1-c1/crash-report
ROOT_DIR=/home/fengwenhan/data/crashfuzz_zk
CUR_CRASH_FILE=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/zk363curCrash
MONITOR=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/monitor.sh
PRETREATMENT=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/prepareEnv.sh
UPDATE_CRASH=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/updateCurCrash.sh
TEST_TIME=80h
#FAULT_CONFIG=1:{ip1,ip2,ip3};2:{ip4,ip5}
FAULT_CSTR=2:{172.40.0.2,172.40.0.3,172.40.0.4,172.40.0.5,172.40.0.6}
#MAP_SIZE=10000
AFL_PORT=12081
#millisecond
#WINDOW_SIZE=1000
HANG_TMOUT=5m
MAX_FAULTS=10

REPLAY_MODE=false

DETERMINE_WAIT_TIME=30000

WRITE_FAV_ENV=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/write-fav-env.sh
COPY_ENV_TO_CLUSTER=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/copy-env-to-cluster.sh

# COPY_LOGS_TO_CONTROLLER=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/copy-logs-to-controller.sh
# CLUSTER_LOGS_IN_CONTROLLER_DIR=/data/fengwenhan/data/crashfuzz_zk_logs

# RECOVERY_MODE=true
RECOVERY_DIR=/data/fengwenhan/data/crashfuzz_zk_recovery

NETWORK_DISCONNECTION=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/network-disconnect.sh
NETWORK_CONNECTION=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk-3.8.1-60/network-connect.sh

EVALUATE_TARGET=CrashFuzzerMinus

