package edu.iscas.tcse.favtrigger.triggering;

public enum TriggerConfigElement {
	PRETREATMENT, WORKLOAD, CLEAN, CRASH_POINTS, MONITOR, UPDATE_FAULT,
	CRASH, RESTART, BUG_REPORT, CUR_FAULT_FILE, MONITOR_DIRS, KILLALL, CHECKER, STRICT_CRASH
}
