WORKLOAD=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/zk1.sh
#WORKLOAD=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/wordcount-crashAM.sh
CRASH=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/crashNode.sh
CHECKER=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/zk1checker.sh
RESTART=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/startNode.sh
#BUG_REPORT=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/crash-report
ROOT_DIR=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/crash-fuzz-0425
CUR_CRASH_FILE=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/zk363curCrash
MONITOR=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/monitor.sh
PRETREATMENT=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/prepareEnv.sh
UPDATE_CRASH=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/updateCurCrash.sh
TEST_TIME=80h
#FAULT_CONFIG=1:{ip1,ip2,ip3};2:{ip4,ip5}
FAULT_CSTR=2:{172.30.0.2,172.30.0.3,172.30.0.4,172.30.0.5,172.30.0.6}
#MAP_SIZE=10000
AFL_PORT=12181
#millisecond
#WINDOW_SIZE=1000
HANG_TMOUT=10m
MAX_FAULTS=10
