WORKLOAD=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/zk1.sh
CRASH=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/crashNode.sh
CHECKER=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/zk1checker.sh
RESTART=//home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/startNode.sh
#BUG_REPORT=/data/gaoyu/crashfuzzer/zk-3.6.3-c1/crash-report
ROOT_DIR=/data/fengwenhan/data/crashfuzz_zk
CUR_CRASH_FILE=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/zk363curCrash
MONITOR=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/monitor.sh
PRETREATMENT=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/prepareEnv.sh
UPDATE_CRASH=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/updateCurCrash.sh
TEST_TIME=80h
#FAULT_CONFIG=1:{ip1,ip2,ip3};2:{ip4,ip5}
FAULT_CSTR=2:{172.30.0.2,172.30.0.3,172.30.0.4,172.30.0.5,172.30.0.6}
#MAP_SIZE=10000
AFL_PORT=12081
#millisecond
#WINDOW_SIZE=1000
HANG_TMOUT=10m
MAX_FAULTS=10

REPLAY_MODE=false

DETERMINE_WAIT_TIME=30000

WRITE_FAV_ENV=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/write-fav-env.sh
COPY_ENV_TO_CLUSTER=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/copy-env-to-cluster.sh

COPY_LOGS_TO_CONTROLLER=/home/fengwenhan/code/crashfuzz-ctrl/script/controller-bash/zk/copy-logs-to-controller.sh
CLUSTER_LOGS_IN_CONTROLLER_DIR=/data/fengwenhan/data/crashfuzz_zk_logs

# RECOVERY_MODE=true
RECOVERY_DIR=/data/fengwenhan/data/crashfuzz_zk_recovery

