# version: "3"
version: "3.5"

# name: fav


services:
  C1ZK1:
    image: fwhdzh/c1zk1
    networks:
      fav-zookeeper:
        ipv4_address: 172.30.0.2
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1ZK1
    hostname: C1ZK1
    cap_add:
      - NET_ADMIN
    # env_file: ~/code/faultfuzz/script/raft-java/.env
    # deploy:
    #   mode: replicated
    #   replicas: 6
    

  C1ZK2:
    image: fwhdzh/c1zk2
    networks:
      fav-zookeeper:
        ipv4_address: 172.30.0.3
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1ZK2
    hostname: C1ZK2
    cap_add:
      - NET_ADMIN

  C1ZK3:
    image: fwhdzh/c1zk3
    networks:
      fav-zookeeper:
        ipv4_address: 172.30.0.4
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1ZK3
    hostname: C1ZK3
    cap_add:
      - NET_ADMIN

  C1ZK4:
    image: fwhdzh/c1zk4
    networks:
      fav-zookeeper:
        ipv4_address: 172.30.0.5
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1ZK4
    hostname: C1ZK4
    cap_add:
      - NET_ADMIN

  C1ZK5:
    image: fwhdzh/c1zk5
    networks:
      fav-zookeeper:
        ipv4_address: 172.30.0.6
    restart: "no"
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    container_name: C1ZK5
    hostname: C1ZK5
    cap_add:
      - NET_ADMIN
    

networks:
  fav-zookeeper:
    name: fav-zookeeper
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/24


# docker-compose -p fav-zk -f /data/fengwenhan/code/faultfuzz/script/controller-bash/zk-3.8.1/zk-compose.yaml up -d
# docker-compose -p fav-zk -f /data/fengwenhan/code/faultfuzz/script/controller-bash/zk-3.8.1/zk-compose.yaml down
# docker-compose -p fav-zk -f /data/fengwenhan/code/faultfuzz/script/controller-bash/zk-3.8.1/zk-compose.yaml exec C1ZK1 /bin/bash