docker exec -t C1ZK1 /bin/bash -ic ". /home/gaoyu/evaluation/zk-3.6.3/bin/zkServer.sh start "
docker exec -t C1ZK2 /bin/bash -ic ". /home/gaoyu/evaluation/zk-3.6.3/bin/zkServer.sh start "
docker exec -t C1ZK3 /bin/bash -ic ". /home/gaoyu/evaluation/zk-3.6.3/bin/zkServer.sh start "
docker exec -t C1ZK4 /bin/bash -ic ". /home/gaoyu/evaluation/zk-3.6.3/bin/zkServer.sh start "
docker exec -t C1ZK5 /bin/bash -ic ". /home/gaoyu/evaluation/zk-3.6.3/bin/zkServer.sh start "