package edu.iscas.CCrashFuzzer;

public enum ConfOption {
	PRETREATMENT, WORKLOAD, MONITOR, UPDATE_CRASH,
	CRASH, RESTART, BUG_REPORT, CUR_CRASH_FILE, MONITOR_DIRS, CHECKER,
	FAULT_CONFIG, TEST_TIME, HANG_TMOUT, MAP_SIZE
}
