WORKLOAD=zk1.sh
CRASH=crashNode.sh
CHECKER=zk1checker.sh
RESTART=startNode.sh
ROOT_DIR=/data/fengwenhan/data/faultfuzz_zk
CUR_FAULT_FILE=zk363curFault
MONITOR=monitor.sh
PRETREATMENT=prepareEnv.sh
UPDATE_FAULT=updateCurFault.sh
TEST_TIME=80h
FAULT_CSTR=2:{172.30.0.2,172.30.0.3,172.30.0.4,172.30.0.5,172.30.0.6}
AFL_PORT=12081
HANG_TMOUT=10m
MAX_FAULTS=10
REPLAY_MODE=false
DETERMINE_WAIT_TIME=30000
# WRITE_FAV_ENV=write-fav-env.sh
# COPY_ENV_TO_CLUSTER=copy-env-to-cluster.sh
# FAV_ENV=fav-env.sh
# RECOVERY_DIR=/data/fengwenhan/data/faultfuzz_zk_recovery
NETWORK_DISCONNECTION=network-disconnect.sh
NETWORK_CONNECTION=network-connect.sh
EVALUATE_TARGET=FaultFuzzer
